spring.application.name=analisis-energetico-api
server.port=${PORT:8080}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized

#Configuracion Servicio de Machine Learning
ml.service.url=${ML_SERVICE_URL:http://localhost:5000/predict}
ml.service.connect-timeout=${ML_CONNET_TIMEOUT:3000}
ml.service.read-timeout=${ML_REAL_TIMEOUT:5000}